# Generated by Django 3.2.8 on 2022-07-10 09:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='District name')),
                ('name_eng', models.CharField(blank=True, max_length=100, unique=True, verbose_name='District name english')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=140, verbose_name='slug')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
            ],
            options={
                'verbose_name': 'Area',
                'verbose_name_plural': 'Areas',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Country name')),
                ('name_eng', models.CharField(blank=True, max_length=30, unique=True, verbose_name='Country name english')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=140, verbose_name='slug')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='OKATO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.PositiveIntegerField(validators=[django.core.validators.RegexValidator(message='Region code must be 2 numbers', regex='^\\d{2}$')], verbose_name='Region code')),
                ('area', models.PositiveIntegerField(validators=[django.core.validators.RegexValidator(message='Area/City code must be 3 numbers', regex='^\\d{3}$')], verbose_name='Area/City code')),
                ('district', models.IntegerField(null=True, validators=[django.core.validators.RegexValidator(message='District code must be 3 numbers', regex='^\\d{3}$')], verbose_name='District code')),
                ('rural', models.IntegerField(null=True, validators=[django.core.validators.RegexValidator(message='Rural locality code must be 3 numbers', regex='^\\d{3}$')], verbose_name='Rural locality')),
                ('section', models.PositiveIntegerField(validators=[django.core.validators.RegexValidator(message='Section code must be 1 numbers', regex='^\\d{1}$')], verbose_name='Section code')),
                ('name', models.CharField(max_length=250, verbose_name='Name of the territory')),
                ('additional_info', models.CharField(blank=True, max_length=80, verbose_name='Additional information')),
                ('desc', models.TextField(blank=True, verbose_name='Description')),
                ('document_num', models.IntegerField(null=True, validators=[django.core.validators.RegexValidator(message='Document number must be 3 numbers', regex='^\\d{3}$')], verbose_name='Document number')),
                ('document_type', models.IntegerField(null=True, validators=[django.core.validators.RegexValidator(message='Document type must be 1 numbers', regex='^\\d{1}$')], verbose_name='Document type')),
                ('date_acceptance', models.DateField(verbose_name='Date of acceptance')),
                ('date_introduction', models.DateField(verbose_name='Date of introduction')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=140, verbose_name='slug')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
            ],
            options={
                'verbose_name': 'OKATO',
                'verbose_name_plural': 'OKATO',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Region name')),
                ('name_eng', models.CharField(blank=True, max_length=100, unique=True, verbose_name='Region name english')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=140, verbose_name='slug')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='addresses.country', verbose_name='Country')),
            ],
            options={
                'verbose_name': 'Region',
                'verbose_name_plural': 'Regions',
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='District name')),
                ('name_eng', models.CharField(blank=True, max_length=100, verbose_name='District name english')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=140, verbose_name='slug')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addresses.area', verbose_name='Area')),
            ],
            options={
                'verbose_name': 'District',
                'verbose_name_plural': 'Districts',
            },
        ),
        migrations.AddField(
            model_name='area',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addresses.region', verbose_name='Region'),
        ),
    ]
