# Generated by Django 3.2.8 on 2022-07-10 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Street name')),
                ('name_eng', models.CharField(blank=True, max_length=100, verbose_name='Street name english')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=140, verbose_name='slug')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addresses.district', verbose_name='Desctrict')),
            ],
            options={
                'verbose_name': 'Street',
                'verbose_name_plural': 'Streets',
            },
        ),
    ]
